name: Update Pluginmaster

on:
  release:
    types: [published]

jobs:
  update-main-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js and Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'
        run: npm install @actions/github

      - name: Get the latest release info and Trigger Target Repo Workflow
        run: |
          LATEST_RELEASE_INFO=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest)
          LATEST_RELEASE_URL=$(echo $LATEST_RELEASE_INFO | jq -r '.assets[0].browser_download_url')
          LATEST_RELEASE_TAG=$(echo $LATEST_RELEASE_INFO | jq -r '.tag_name')
          DOWNLOAD_COUNT=$(echo $LATEST_RELEASE_INFO | jq -r '[.assets[].download_count] | @csv')

          if [ -z "${{ secrets.PERSONAL_ACCESS_TOKEN }}" ]; then
            echo "PERSONAL_ACCESS_TOKEN is not set."
            exit 1
          fi

          pluginName="NNKicker";
          curl -X POST -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          --data '{"event_type": "update-plugin", "client_payload": {"tag": "'$LATEST_RELEASE_TAG'", "url": "'$LATEST_RELEASE_URL'", "name": "'$pluginName'", "downloadcount": "'$DOWNLOAD_COUNT'"}}' \
          https://api.github.com/repos/AtmoOmen/DalamudPlugins/dispatches
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
