name: Update Main Repo

on:
  release:
    types: [published]

jobs:
  update-main-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install @actions/github

      - name: Get the latest release info
        id: get-release
        run: |
          LATEST_RELEASE_INFO=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest)
          LATEST_RELEASE_URL=$(echo $LATEST_RELEASE_INFO | jq -r '.assets[0].browser_download_url')
          LATEST_RELEASE_TAG=$(echo $LATEST_RELEASE_INFO | jq -r '.tag_name')
          echo "::set-output name=url::$LATEST_RELEASE_URL"
          echo "::set-output name=tag::$LATEST_RELEASE_TAG"

      - name: Check if PERSONAL_ACCESS_TOKEN is set
        run: |
          if [ -z "${{ secrets.PERSONAL_ACCESS_TOKEN }}" ]; then
            echo "PERSONAL_ACCESS_TOKEN is not set."
          else
            echo "PERSONAL_ACCESS_TOKEN is set."
          fi

      - name: Trigger Target Repo Workflow
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          --data '{"event_type": "update-plugin", "client_payload": {"tag": "${{ steps.get-release.outputs.tag }}", "url": "${{ steps.get-release.outputs.url }}"} }' \
          https://api.github.com/repos/AtmoOmen/DalamudPlugins/dispatches
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
